
// countryMatrix is the collection; array of committees (each row is a committee)
// committee Object is a row; two columns/keys, one name and other array of country and its status

const countryMatrix = [
    {
       "committee":"AU",
       "countries":[
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Angola",
             "assigned":""
          },
          {
             "name":"Benin",
             "assigned":""
          },
          {
             "name":"Botswana",
             "assigned":""
          },
          {
             "name":"Burkina Faso",
             "assigned":""
          },
          {
             "name":"Burundi",
             "assigned":""
          },
          {
             "name":"Cameroon",
             "assigned":""
          },
          {
             "name":"Cabo Verde",
             "assigned":""
          },
          {
             "name":"Central African Republic",
             "assigned":""
          },
          {
             "name":"Chad",
             "assigned":""
          },
          {
             "name":"Comoros",
             "assigned":""
          },
          {
             "name":"Côte d'Ivoire",
             "assigned":""
          },
          {
             "name":"Democratic Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Djibouti",
             "assigned":""
          },
          {
             "name":"Egypt",
             "assigned":""
          },
          {
             "name":"Equatorial Guinea",
             "assigned":""
          },
          {
             "name":"Eritrea",
             "assigned":""
          },
          {
             "name":"Eswatini",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Gabon",
             "assigned":""
          },
          {
             "name":"Gambia",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"Guinea",
             "assigned":""
          },
          {
             "name":"Guinea-Bissau",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Lesotho",
             "assigned":""
          },
          {
             "name":"Liberia",
             "assigned":""
          },
          {
             "name":"Libya",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malawi",
             "assigned":""
          },
          {
             "name":"Mali",
             "assigned":""
          },
          {
             "name":"Mauritania",
             "assigned":""
          },
          {
             "name":"Mauritius",
             "assigned":""
          },
          {
             "name":"Morocco",
             "assigned":""
          },
          {
             "name":"Mozambique",
             "assigned":""
          },
          {
             "name":"Namibia",
             "assigned":""
          },
          {
             "name":"Niger",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Rwanda",
             "assigned":""
          },
          {
             "name":"Sahrawi Arab Democratic Republic",
             "assigned":""
          },
          {
             "name":"São Tomé and Príncipe",
             "assigned":""
          },
          {
             "name":"Senegal",
             "assigned":""
          },
          {
             "name":"Seychelles",
             "assigned":""
          },
          {
             "name":"Sierra Leone",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"South Sudan",
             "assigned":""
          },
          {
             "name":"Sudan",
             "assigned":""
          },
          {
             "name":"Tanzania",
             "assigned":""
          },
          {
             "name":"Togo",
             "assigned":""
          },
          {
             "name":"Tunisia",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Zambia",
             "assigned":""
          },
          {
             "name":"Zimbabwe",
             "assigned":""
          }
       ]
    },
    {
       "committee":"Business",
       "countries":[
          {
             "name":"JP Morgan Chase",
             "assigned":""
          },
          {
             "name":"Goldman Sachs",
             "assigned":""
          },
          {
             "name":"Citigroup",
             "assigned":""
          },
          {
             "name":"Barclays",
             "assigned":""
          },
          {
             "name":"Wirex",
             "assigned":""
          },
          {
             "name":"Coinbase",
             "assigned":""
          },
          {
             "name":"Square",
             "assigned":""
          },
          {
             "name":"Antpool",
             "assigned":""
          },
          {
             "name":"Berkshire Hathaway",
             "assigned":""
          },
          {
             "name":"Industrial and Commercial Bank of China",
             "assigned":""
          },
          {
             "name":"Mt. Gox",
             "assigned":""
          },
          {
             "name":"PolyNetwork",
             "assigned":""
          },
          {
             "name":"Sberbank",
             "assigned":""
          },
          {
             "name":"Toronto-Dominion Bank",
             "assigned":""
          },
          {
             "name":"PayPal",
             "assigned":""
          },
          {
             "name":"Silvergate Capital",
             "assigned":""
          },
          {
             "name":"Alibaba",
             "assigned":""
          },
          {
             "name":"Amazon",
             "assigned":""
          },
          {
             "name":"Nvidia",
             "assigned":""
          },
          {
             "name":"HSBC",
             "assigned":""
          }
       ]
    },
    {
       "committee":"C40",
       "countries":[
          {
             "name":"Accra",
             "assigned":""
          },
          {
             "name":"Addis Ababa",
             "assigned":""
          },
          {
             "name":"Amman",
             "assigned":""
          },
          {
             "name":"Amsterdam",
             "assigned":""
          },
          {
             "name":"Athens",
             "assigned":""
          },
          {
             "name":"Auckland",
             "assigned":""
          },
          {
             "name":"Bangkok",
             "assigned":""
          },
          {
             "name":"Barcelona",
             "assigned":""
          },
          {
             "name":"Beijing",
             "assigned":""
          },
          {
             "name":"Berlin",
             "assigned":""
          },
          {
             "name":"Bogotá",
             "assigned":""
          },
          {
             "name":"Boston",
             "assigned":""
          },
          {
             "name":"Buenos Aires",
             "assigned":""
          },
          {
             "name":"Chicago",
             "assigned":""
          },
          {
             "name":"Copenhagen",
             "assigned":""
          },
          {
             "name":"Curitiba",
             "assigned":""
          },
          {
             "name":"Delhi NCT",
             "assigned":""
          },
          {
             "name":"Dhaka North",
             "assigned":""
          },
          {
             "name":"Dubai",
             "assigned":""
          },
          {
             "name":"Durban (eThekwini)",
             "assigned":""
          },
          {
             "name":"Freetown",
             "assigned":""
          },
          {
             "name":"Hangzhou",
             "assigned":""
          },
          {
             "name":"Heidelberg",
             "assigned":""
          },
          {
             "name":"Ho Chi Min City",
             "assigned":""
          },
          {
             "name":"Hong Kong",
             "assigned":""
          },
          {
             "name":"Houston",
             "assigned":""
          },
          {
             "name":"Istanbul",
             "assigned":""
          },
          {
             "name":"Jakarta",
             "assigned":""
          },
          {
             "name":"Johannesberg",
             "assigned":""
          },
          {
             "name":"Karachi",
             "assigned":""
          },
          {
             "name":"Kuala Lumpur",
             "assigned":""
          },
          {
             "name":"Lagos",
             "assigned":""
          },
          {
             "name":"Lima",
             "assigned":""
          },
          {
             "name":"Lisbon",
             "assigned":""
          },
          {
             "name":"London",
             "assigned":""
          },
          {
             "name":"Los Angeles",
             "assigned":""
          },
          {
             "name":"Madrid",
             "assigned":""
          },
          {
             "name":"Melbourne",
             "assigned":""
          },
          {
             "name":"Mexico City",
             "assigned":""
          },
          {
             "name":"Milan",
             "assigned":""
          },
          {
             "name":"Moscow",
             "assigned":""
          },
          {
             "name":"Mumbai",
             "assigned":""
          },
          {
             "name":"Nairobi",
             "assigned":""
          },
          {
             "name":"New Orleans",
             "assigned":""
          },
          {
             "name":"New York",
             "assigned":""
          },
          {
             "name":"Oslo",
             "assigned":""
          },
          {
             "name":"Paris",
             "assigned":""
          },
          {
             "name":"Phoenix",
             "assigned":""
          },
          {
             "name":"Qingdao",
             "assigned":""
          },
          {
             "name":"Quebec",
             "assigned":""
          },
          {
             "name":"Quezon City",
             "assigned":""
          },
          {
             "name":"Quito",
             "assigned":""
          },
          {
             "name":"Rio de Janeiro",
             "assigned":""
          },
          {
             "name":"Rome",
             "assigned":""
          },
          {
             "name":"Rotterdam",
             "assigned":""
          },
          {
             "name":"San Francisco",
             "assigned":""
          },
          {
             "name":"Santiago",
             "assigned":""
          },
          {
             "name":"São Paulo",
             "assigned":""
          },
          {
             "name":"Seattle",
             "assigned":""
          },
          {
             "name":"Seoul",
             "assigned":""
          },
          {
             "name":"Shenzhen",
             "assigned":""
          },
          {
             "name":"Singapore",
             "assigned":""
          },
          {
             "name":"Stockholm",
             "assigned":""
          },
          {
             "name":"Sydney",
             "assigned":""
          },
          {
             "name":"Tel Aviv - Yafo",
             "assigned":""
          },
          {
             "name":"Tokyo",
             "assigned":""
          },
          {
             "name":"Toronto",
             "assigned":""
          },
          {
             "name":"Vancouver",
             "assigned":""
          },
          {
             "name":"Warsaw",
             "assigned":""
          },
          {
             "name":"\"Washington, DC\"",
             "assigned":""
          }
       ]
    },
    {
       "committee":"CIS",
       "countries":[
          {
             "name":"Armenia A",
             "assigned":""
          },
          {
             "name":"Armenia B",
             "assigned":""
          },
          {
             "name":"Azerbaijan A",
             "assigned":""
          },
          {
             "name":"Azerbaijan B",
             "assigned":""
          },
          {
             "name":"Belarus A",
             "assigned":""
          },
          {
             "name":"Belarus B",
             "assigned":""
          },
          {
             "name":"Kazakhstan A",
             "assigned":""
          },
          {
             "name":"Kazakhstan B",
             "assigned":""
          },
          {
             "name":"Kyrgyzstan A",
             "assigned":""
          },
          {
             "name":"Kyrgyzstan B",
             "assigned":""
          },
          {
             "name":"Moldova A",
             "assigned":""
          },
          {
             "name":"Moldova B",
             "assigned":""
          },
          {
             "name":"Russian Federation A",
             "assigned":""
          },
          {
             "name":"Russian Federation B",
             "assigned":""
          },
          {
             "name":"Tajikistan A",
             "assigned":""
          },
          {
             "name":"Tajikistan B",
             "assigned":""
          },
          {
             "name":"Uzbekistan A",
             "assigned":""
          },
          {
             "name":"Uzbekistan B",
             "assigned":""
          }
       ]
    },
    {
       "committee":"DISEC",
       "countries":[
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belarus",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Bolivia",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Bulgaria",
             "assigned":""
          },
          {
             "name":"Burundi",
             "assigned":""
          },
          {
             "name":"Cambodia",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"Colombia",
             "assigned":""
          },
          {
             "name":"Côte d'Ivoire",
             "assigned":""
          },
          {
             "name":"Croatia",
             "assigned":""
          },
          {
             "name":"Cuba",
             "assigned":""
          },
          {
             "name":"Czech Republic",
             "assigned":""
          },
          {
             "name":"Democratic People's Republic of Korea",
             "assigned":""
          },
          {
             "name":"Democratic Republic of Congo",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Djibouti",
             "assigned":""
          },
          {
             "name":"Ecuador",
             "assigned":""
          },
          {
             "name":"Egypt",
             "assigned":""
          },
          {
             "name":"El Salvador",
             "assigned":""
          },
          {
             "name":"Estonia",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Guatemala",
             "assigned":""
          },
          {
             "name":"Guinea",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"Iceland",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iran",
             "assigned":""
          },
          {
             "name":"Iraq",
             "assigned":""
          },
          {
             "name":"Ireland",
             "assigned":""
          },
          {
             "name":"Israel",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Jamaica",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Lebanon",
             "assigned":""
          },
          {
             "name":"Libya",
             "assigned":""
          },
          {
             "name":"Luxembourg",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malawi",
             "assigned":""
          },
          {
             "name":"Malaysia",
             "assigned":""
          },
          {
             "name":"Maldives",
             "assigned":""
          },
          {
             "name":"Mali",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Morocco",
             "assigned":""
          },
          {
             "name":"Nepal",
             "assigned":""
          },
          {
             "name":"Netherlands",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"Papua New Guinea",
             "assigned":""
          },
          {
             "name":"People's Republic of China",
             "assigned":""
          },
          {
             "name":"Peru",
             "assigned":""
          },
          {
             "name":"Philippines",
             "assigned":""
          },
          {
             "name":"Poland",
             "assigned":""
          },
          {
             "name":"Portugal",
             "assigned":""
          },
          {
             "name":"Qatar",
             "assigned":""
          },
          {
             "name":"Republic of Korea",
             "assigned":""
          },
          {
             "name":"Romania",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Saudi Arabia",
             "assigned":""
          },
          {
             "name":"Singapore",
             "assigned":""
          },
          {
             "name":"Slovakia",
             "assigned":""
          },
          {
             "name":"Slovenia",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"South Sudan",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sudan",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United Arab Emirates",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States of America",
             "assigned":""
          },
          {
             "name":"Vietnam",
             "assigned":""
          },
          {
             "name":"Yemen",
             "assigned":""
          },
          {
             "name":"Zimbabwe",
             "assigned":""
          }
       ]
    },
    {
       "committee":"EAS",
       "countries":[
          {
             "name":"Australia A",
             "assigned":""
          },
          {
             "name":"Australia B",
             "assigned":""
          },
          {
             "name":"Brunei A",
             "assigned":""
          },
          {
             "name":"Brunei B",
             "assigned":""
          },
          {
             "name":"Cambodia A",
             "assigned":""
          },
          {
             "name":"Cambodia B",
             "assigned":""
          },
          {
             "name":"China A",
             "assigned":""
          },
          {
             "name":"China B",
             "assigned":""
          },
          {
             "name":"India A",
             "assigned":""
          },
          {
             "name":"India B",
             "assigned":""
          },
          {
             "name":"Indonesia A",
             "assigned":""
          },
          {
             "name":"Indonesia B",
             "assigned":""
          },
          {
             "name":"Japan A",
             "assigned":""
          },
          {
             "name":"Japan B",
             "assigned":""
          },
          {
             "name":"Laos A",
             "assigned":""
          },
          {
             "name":"Laos B",
             "assigned":""
          },
          {
             "name":"Malaysia A",
             "assigned":""
          },
          {
             "name":"Malaysia B",
             "assigned":""
          },
          {
             "name":"Myanmar A",
             "assigned":""
          },
          {
             "name":"Myanmar B",
             "assigned":""
          },
          {
             "name":"New Zealand A",
             "assigned":""
          },
          {
             "name":"New Zealand B",
             "assigned":""
          },
          {
             "name":"Philippines A",
             "assigned":""
          },
          {
             "name":"Philippines B",
             "assigned":""
          },
          {
             "name":"Republic of Korea A",
             "assigned":""
          },
          {
             "name":"Republic of Korea B",
             "assigned":""
          },
          {
             "name":"Russia A",
             "assigned":""
          },
          {
             "name":"Russia B",
             "assigned":""
          },
          {
             "name":"Singapore A",
             "assigned":""
          },
          {
             "name":"Singapore B",
             "assigned":""
          },
          {
             "name":"Thailand A",
             "assigned":""
          },
          {
             "name":"Thailand B",
             "assigned":""
          },
          {
             "name":"United States A",
             "assigned":""
          },
          {
             "name":"United States B",
             "assigned":""
          },
          {
             "name":"Vietnam A",
             "assigned":""
          },
          {
             "name":"Vietnam B",
             "assigned":""
          }
       ]
    },
    {
       "committee":"ECC",
       "countries":[
          {
             "name":"Position 1",
             "assigned":""
          },
          {
             "name":"Position 2",
             "assigned":""
          },
          {
             "name":"Position 3",
             "assigned":""
          },
          {
             "name":"Position 4",
             "assigned":""
          },
          {
             "name":"Position 5",
             "assigned":""
          },
          {
             "name":"Position 6",
             "assigned":""
          },
          {
             "name":"Position 7",
             "assigned":""
          },
          {
             "name":"Position 8",
             "assigned":""
          },
          {
             "name":"Position 9",
             "assigned":""
          },
          {
             "name":"Position 10",
             "assigned":""
          },
          {
             "name":"Position 11",
             "assigned":""
          },
          {
             "name":"Position 12",
             "assigned":""
          },
          {
             "name":"Position 13",
             "assigned":""
          },
          {
             "name":"Position 14",
             "assigned":""
          },
          {
             "name":"Position 15",
             "assigned":""
          },
          {
             "name":"Position 16",
             "assigned":""
          },
          {
             "name":"Position 17",
             "assigned":""
          },
          {
             "name":"Position 18",
             "assigned":""
          },
          {
             "name":"Position 19",
             "assigned":""
          },
          {
             "name":"Position 20",
             "assigned":""
          },
          {
             "name":"Position 21",
             "assigned":""
          },
          {
             "name":"Position 22",
             "assigned":""
          },
          {
             "name":"Position 23",
             "assigned":""
          },
          {
             "name":"Position 24",
             "assigned":""
          },
          {
             "name":"Position 25",
             "assigned":""
          },
          {
             "name":"Position 26",
             "assigned":""
          },
          {
             "name":"Position 27",
             "assigned":""
          },
          {
             "name":"Position 28",
             "assigned":""
          },
          {
             "name":"Position 29",
             "assigned":""
          },
          {
             "name":"Position 30",
             "assigned":""
          }
       ]
    },
    {
       "committee":"FCC",
       "countries":[
          {
             "name":"Agent Champagne",
             "assigned":""
          },
          {
             "name":"Agent Gin",
             "assigned":""
          },
          {
             "name":"Agent Tequila",
             "assigned":""
          },
          {
             "name":"Agent Whiskey",
             "assigned":""
          },
          {
             "name":"Arthur",
             "assigned":""
          },
          {
             "name":"Brandy",
             "assigned":""
          },
          {
             "name":"Cider",
             "assigned":""
          },
          {
             "name":"Cognac",
             "assigned":""
          },
          {
             "name":"Downing Street Chief of Staff",
             "assigned":""
          },
          {
             "name":"Eggsy (Galahad)",
             "assigned":""
          },
          {
             "name":"Gawain",
             "assigned":""
          },
          {
             "name":"General Mccoy",
             "assigned":""
          },
          {
             "name":"Ginger Ale",
             "assigned":""
          },
          {
             "name":"Harry Hart (Formerly Galahad)",
             "assigned":""
          },
          {
             "name":"Lancelot",
             "assigned":""
          },
          {
             "name":"Merlin",
             "assigned":""
          },
          {
             "name":"Percival",
             "assigned":""
          },
          {
             "name":"President of the United States",
             "assigned":""
          },
          {
             "name":"Prime Minister of the United Kingdom",
             "assigned":""
          },
          {
             "name":"Secretary of Defence",
             "assigned":""
          }
       ]
    },
    {
       "committee":"HCC",
       "countries":[
          {
             "name":"Alexander Hamilton",
             "assigned":""
          },
          {
             "name":"Benjamin Franklin",
             "assigned":""
          },
          {
             "name":"Benjamin Harrison",
             "assigned":""
          },
          {
             "name":"Benjamin Rush",
             "assigned":""
          },
          {
             "name":"George Mason",
             "assigned":""
          },
          {
             "name":"George Washington",
             "assigned":""
          },
          {
             "name":"Gouverneur Morris",
             "assigned":""
          },
          {
             "name":"James Madison",
             "assigned":""
          },
          {
             "name":"James Monroe",
             "assigned":""
          },
          {
             "name":"John Adams",
             "assigned":""
          },
          {
             "name":"John Dickinson",
             "assigned":""
          },
          {
             "name":"John Hancock",
             "assigned":""
          },
          {
             "name":"John Jay",
             "assigned":""
          },
          {
             "name":"John Marshall",
             "assigned":""
          },
          {
             "name":"Marquis de Lafayette",
             "assigned":""
          },
          {
             "name":"Patrick Henry",
             "assigned":""
          },
          {
             "name":"Richard Henry Lee",
             "assigned":""
          },
          {
             "name":"Roger Sherman",
             "assigned":""
          },
          {
             "name":"Samuel Adams",
             "assigned":""
          },
          {
             "name":"Thomas Jefferson",
             "assigned":""
          },
          {
             "name":"Thomas Paine",
             "assigned":""
          }
       ]
    },
    {
       "committee":"IPC",
       "countries":[
          {
             "name":"New York Times",
             "assigned":""
          },
          {
             "name":"CNN",
             "assigned":""
          },
          {
             "name":"Xinhua News Agency",
             "assigned":""
          },
          {
             "name":"The Onion",
             "assigned":""
          },
          {
             "name":"The Globe and Mail",
             "assigned":""
          },
          {
             "name":"Fox News",
             "assigned":""
          },
          {
             "name":"Russia Today",
             "assigned":""
          },
          {
             "name":"Al Jazeera",
             "assigned":""
          },
          {
             "name":"BBC",
             "assigned":""
          },
          {
             "name":"Euronews",
             "assigned":""
          }
       ]
    },
    {
       "committee":"JCC Bloc A",
       "countries":[
          {
             "name":"Tsar of Russia: Peter the Great",
             "assigned":""
          },
          {
             "name":"Russian Generalissimo: Aleksander Danilovich Menshikov",
             "assigned":""
          },
          {
             "name":"Russian Field Marshal: Boris Petrovich Sheremetev",
             "assigned":""
          },
          {
             "name":"Russian Foreign Minister: Yemelyan Ignatievich Ukraintsev",
             "assigned":""
          },
          {
             "name":"Russian Admiral: Fyodor Matveyevich Apraksin",
             "assigned":""
          },
          {
             "name":"King of Poland: Grand Duke of Lithuania, and Elector of Saxony: Augustus II",
             "assigned":""
          },
          {
             "name":"Polish Colonel: Stanisław Chomętowski",
             "assigned":""
          },
          {
             "name":"Polish–Lithuanian Field Marshal: Michał Serwacy Wiśniowiecki",
             "assigned":""
          },
          {
             "name":"King of Denmark and Norway: Frederick IV",
             "assigned":""
          },
          {
             "name":"Danish Admiral: Ulrik Christian Gyldenløve",
             "assigned":""
          },
          {
             "name":"Danish Major General: Jørgen Rantzau",
             "assigned":""
          },
          {
             "name":"King of Prussia and Elector of Brandenburg: Frederick William I",
             "assigned":""
          },
          {
             "name":"Prussian Field Marshal: Leopold I",
             "assigned":""
          },
          {
             "name":"Prussian Prime Minister: Johann Kasimir Kolbe von Wartenberg",
             "assigned":""
          },
          {
             "name":"Prussian Field Marshal: Friedrich Wilhelm von Grumbkow",
             "assigned":""
          }
       ]
    },
    {
       "committee":"JCC Bloc B",
       "countries":[
          {
             "name":"King of Sweden: Charles XII",
             "assigned":""
          },
          {
             "name":"King of England, Scotland, and Ireland: William III",
             "assigned":""
          },
          {
             "name":"Polish Nobleman: Stanisław Leszczyński",
             "assigned":""
          },
          {
             "name":"Swedish Generalissimo: Frederick I",
             "assigned":""
          },
          {
             "name":"Swedish Marshal of the Realm: Carl Piper",
             "assigned":""
          },
          {
             "name":"Duke of Hostein-Gottorp: Frederick IV",
             "assigned":""
          },
          {
             "name":"Swedish Field Marshal: Carl Gustav Rehnskiöld",
             "assigned":""
          },
          {
             "name":"Polish Nobleman: Józef Potocki",
             "assigned":""
          },
          {
             "name":"Swedish Field Marshal: Magnus Stenbock",
             "assigned":""
          },
          {
             "name":"Grand Hetman of Lithuania: Jan Kazimierz Sapieha the Younger",
             "assigned":""
          },
          {
             "name":"Hetman of Zaporizhian Host: Ivan Mazepa",
             "assigned":""
          },
          {
             "name":"Hetman of Ukraine: Pylyp Orlyk",
             "assigned":""
          },
          {
             "name":"Swedish General: Adam Ludwig Lewenhaupt",
             "assigned":""
          },
          {
             "name":"Swedish Admiral-General: Hans Wachtmeister",
             "assigned":""
          },
          {
             "name":"Ottoman Foreign Minister: Rami Mehmed Pasha",
             "assigned":""
          }
       ]
    },
    {
       "committee":"NGO",
       "countries":[
          {
             "name":"Partners in Health",
             "assigned":""
          },
          {
             "name":"Root Capital",
             "assigned":""
          },
          {
             "name":"Cure Violence",
             "assigned":""
          },
          {
             "name":"Mercy Corps",
             "assigned":""
          },
          {
             "name":"Acumen Fund",
             "assigned":""
          },
          {
             "name":"Care International",
             "assigned":""
          },
          {
             "name":"International Red Cross and Red Crescent Movement",
             "assigned":""
          },
          {
             "name":"Humans Rights Watch",
             "assigned":""
          },
          {
             "name":"Amnesty International",
             "assigned":""
          },
          {
             "name":"Ceres",
             "assigned":""
          }
       ]
    },
    {
       "committee":"SOCHUM",
       "countries":[
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Albania",
             "assigned":""
          },
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Argentina",
             "assigned":""
          },
          {
             "name":"Armenia",
             "assigned":""
          },
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Azerbaijan",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Benin",
             "assigned":""
          },
          {
             "name":"Bolivia",
             "assigned":""
          },
          {
             "name":"Bosnia and Herzegovina",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Brunei",
             "assigned":""
          },
          {
             "name":"Cambodia",
             "assigned":""
          },
          {
             "name":"Cameroon",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"Chad",
             "assigned":""
          },
          {
             "name":"Chile",
             "assigned":""
          },
          {
             "name":"Colombia",
             "assigned":""
          },
          {
             "name":"Côte D'Ivoire",
             "assigned":""
          },
          {
             "name":"Croatia",
             "assigned":""
          },
          {
             "name":"Czech Republic",
             "assigned":""
          },
          {
             "name":"Democratic People's Republic of Korea",
             "assigned":""
          },
          {
             "name":"Democratic Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Egypt",
             "assigned":""
          },
          {
             "name":"Eritrea",
             "assigned":""
          },
          {
             "name":"Estonia",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Georgia",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iraq",
             "assigned":""
          },
          {
             "name":"Ireland",
             "assigned":""
          },
          {
             "name":"Islamic Republic of Iran",
             "assigned":""
          },
          {
             "name":"Israel",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Jamaica",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Kazakhstan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Kuwait",
             "assigned":""
          },
          {
             "name":"Laos",
             "assigned":""
          },
          {
             "name":"Lativa",
             "assigned":""
          },
          {
             "name":"Liberia",
             "assigned":""
          },
          {
             "name":"Lithuania",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malaysia",
             "assigned":""
          },
          {
             "name":"Mali",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Mongolia",
             "assigned":""
          },
          {
             "name":"Morocco",
             "assigned":""
          },
          {
             "name":"Myanmar",
             "assigned":""
          },
          {
             "name":"Netherlands",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"People's Republic of China",
             "assigned":""
          },
          {
             "name":"Peru",
             "assigned":""
          },
          {
             "name":"Philippines",
             "assigned":""
          },
          {
             "name":"Poland",
             "assigned":""
          },
          {
             "name":"Portugal",
             "assigned":""
          },
          {
             "name":"Republic of Korea",
             "assigned":""
          },
          {
             "name":"Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Romania",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Rwanda",
             "assigned":""
          },
          {
             "name":"Saudi Arabia",
             "assigned":""
          },
          {
             "name":"Singapore",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"Tunisia",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United Arab Emirates",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States of America",
             "assigned":""
          },
          {
             "name":"Uzbekistan",
             "assigned":""
          },
          {
             "name":"Vietnam",
             "assigned":""
          },
          {
             "name":"Yemen",
             "assigned":""
          }
       ]
    },
    {
       "committee":"SPECPOL",
       "countries":[
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Albania",
             "assigned":""
          },
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Angola",
             "assigned":""
          },
          {
             "name":"Argentina",
             "assigned":""
          },
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belarus",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Bulgaria",
             "assigned":""
          },
          {
             "name":"Cambodia",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"Chad",
             "assigned":""
          },
          {
             "name":"Chile",
             "assigned":""
          },
          {
             "name":"Colombia",
             "assigned":""
          },
          {
             "name":"Costa Rica",
             "assigned":""
          },
          {
             "name":"Cuba",
             "assigned":""
          },
          {
             "name":"Czech Republic",
             "assigned":""
          },
          {
             "name":"Democratic People's Republic of Korea",
             "assigned":""
          },
          {
             "name":"Democratic Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Dominican Republic",
             "assigned":""
          },
          {
             "name":"Ecuador",
             "assigned":""
          },
          {
             "name":"Egypt",
             "assigned":""
          },
          {
             "name":"Estonia",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Fiji",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Haiti",
             "assigned":""
          },
          {
             "name":"Honduras",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"Iceland",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iran",
             "assigned":""
          },
          {
             "name":"Iraq",
             "assigned":""
          },
          {
             "name":"Ireland",
             "assigned":""
          },
          {
             "name":"Israel",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Jamaica",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Jordan",
             "assigned":""
          },
          {
             "name":"Kazakhstan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Latvia",
             "assigned":""
          },
          {
             "name":"Libya",
             "assigned":""
          },
          {
             "name":"Luxembourg",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malaysia",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Morocco",
             "assigned":""
          },
          {
             "name":"Myanmar",
             "assigned":""
          },
          {
             "name":"Nepal",
             "assigned":""
          },
          {
             "name":"Netherlands",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"Panama",
             "assigned":""
          },
          {
             "name":"People's Republic of China",
             "assigned":""
          },
          {
             "name":"Philippines",
             "assigned":""
          },
          {
             "name":"Poland",
             "assigned":""
          },
          {
             "name":"Portugal",
             "assigned":""
          },
          {
             "name":"Republic of Korea",
             "assigned":""
          },
          {
             "name":"Romania",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Saudi Arabia",
             "assigned":""
          },
          {
             "name":"Singapore",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sri Lanka",
             "assigned":""
          },
          {
             "name":"Sudan",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Tanzania",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"Tunisia",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United Arab Emirates",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States of America",
             "assigned":""
          },
          {
             "name":"Venezuela",
             "assigned":""
          },
          {
             "name":"Vietnam",
             "assigned":""
          },
          {
             "name":"Yemen",
             "assigned":""
          },
          {
             "name":"Zimbabwe",
             "assigned":""
          }
       ]
    },
    {
       "committee":"UN Women",
       "countries":[
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Bhutan",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Burundi",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"China",
             "assigned":""
          },
          {
             "name":"Democratic Republic of the Congo",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Haiti",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"Iceland",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Iran",
             "assigned":""
          },
          {
             "name":"Iraq",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Jordan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Latvia",
             "assigned":""
          },
          {
             "name":"Lebanon",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Mozambique",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nicaragua",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"Phillipines",
             "assigned":""
          },
          {
             "name":"Poland",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Saudi Arabia",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"South Korea",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"Tunisia",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States",
             "assigned":""
          },
          {
             "name":"Venezuela",
             "assigned":""
          },
          {
             "name":"Yemen",
             "assigned":""
          }
       ]
    },
    {
       "committee":"UNDP",
       "countries":[
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belarus",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Botswana",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Bulgaria",
             "assigned":""
          },
          {
             "name":"Cameroon",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"China",
             "assigned":""
          },
          {
             "name":"Colombia",
             "assigned":""
          },
          {
             "name":"Cuba",
             "assigned":""
          },
          {
             "name":"Czech Republic",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Estonia",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Gambia",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Guatemala",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iran",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Kuwait",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Peru",
             "assigned":""
          },
          {
             "name":"Republic of Korea",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Rwanda",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"The Netherlands",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States",
             "assigned":""
          },
          {
             "name":"Vanuatu",
             "assigned":""
          }
       ]
    },
    {
       "committee":"UNESCO",
       "countries":[
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Australia",
             "assigned":""
          },
          {
             "name":"Azerbaijan",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Bolivia",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Cameroon",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"China",
             "assigned":""
          },
          {
             "name":"Croatia",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Ecuador",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Georgia",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Iceland",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iran",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Lithuania",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malaysia",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Netherlands",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"Papua New Guinea",
             "assigned":""
          },
          {
             "name":"Peru",
             "assigned":""
          },
          {
             "name":"Portugal",
             "assigned":""
          },
          {
             "name":"Romania",
             "assigned":""
          },
          {
             "name":"Russian Federation",
             "assigned":""
          },
          {
             "name":"Rwanda",
             "assigned":""
          },
          {
             "name":"Saudi Arabia",
             "assigned":""
          },
          {
             "name":"Serbia",
             "assigned":""
          },
          {
             "name":"Singapore",
             "assigned":""
          },
          {
             "name":"Slovenia",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Philippines",
             "assigned":""
          },
          {
             "name":"Tunisia",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United Arab Emirates",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States of America",
             "assigned":""
          },
          {
             "name":"Venezuela",
             "assigned":""
          },
          {
             "name":"Vietnam",
             "assigned":""
          },
          {
             "name":"Zimbabwe",
             "assigned":""
          }
       ]
    },
    {
       "committee":"UNSC",
       "countries":[
          {
             "name":"Albania",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"China",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Gabon",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Ireland",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Russia",
             "assigned":""
          },
          {
             "name":"United Arab Emirates",
             "assigned":""
          },
          {
             "name":"United Kingdom",
             "assigned":""
          },
          {
             "name":"United States of America",
             "assigned":""
          }
       ]
    },
    {
       "committee":"US House of Rep.",
       "countries":[
          {
             "name":"Terri Sewell (D-AL, 7th district)*",
             "assigned":""
          },
          {
             "name":"Don Young (R-AK, 1st district)*",
             "assigned":""
          },
          {
             "name":"Ruben Gallego (D-AZ, 7th district)*",
             "assigned":""
          },
          {
             "name":"Carlos A. Gimenez (R-FL, 26th district)",
             "assigned":""
          },
          {
             "name":"Speaker of the House of Representatives — Nancy Pelosi (D-CA, 12th district)*",
             "assigned":""
          },
          {
             "name":"Bill Foster (D-IL, 11th district)",
             "assigned":""
          },
          {
             "name":"House Minority Leader — Kevin McCarthy (R-CA, 23rd district)*",
             "assigned":""
          },
          {
             "name":"Majority Leader of the United States House of Representatives — Steny Hoyer (D-MD, 5th district)",
             "assigned":""
          },
          {
             "name":"Victoria Spartz (R-IN, 5tth district)",
             "assigned":""
          },
          {
             "name":"Maxine Waters (D-CA, 43rd district)*",
             "assigned":""
          },
          {
             "name":"Jim Himes (D-CT, 4th district)",
             "assigned":""
          },
          {
             "name":"Frederica Wilson (D-FL, 24th district)",
             "assigned":""
          },
          {
             "name":"Gregory Steube (R-FL,17th district)*",
             "assigned":""
          },
          {
             "name":"Mark Takano (D-CA, 41st district)",
             "assigned":""
          },
          {
             "name":"James Baird (R-IN, 4th district)",
             "assigned":""
          },
          {
             "name":"Randy Feenstra (R-IA, 4th district)",
             "assigned":""
          },
          {
             "name":"Raul Grijalva (D-AZ, 3rd district)",
             "assigned":""
          },
          {
             "name":"Kweisi Mfume (D-MD, 7th district)",
             "assigned":""
          },
          {
             "name":"Haley M. Stevens (D-MI, 11th district)",
             "assigned":""
          },
          {
             "name":"House Minority Whip — Steve Scalise (R-LA, 1st district)",
             "assigned":""
          },
          {
             "name":"Joe Wilson (R-SC, 2nd district)",
             "assigned":""
          },
          {
             "name":"House Majority Leader — Steny Hoyer (D-MA, 5th district)",
             "assigned":""
          },
          {
             "name":"Ayanna Pressley (D-MA, 7th district)",
             "assigned":""
          },
          {
             "name":"Ilhan Omar (D-MN, 5th district)*",
             "assigned":""
          },
          {
             "name":"Chair Suzanne Bonamici (D-OR, 1st district)",
             "assigned":""
          },
          {
             "name":"Frederica S. Wilson (D-FL, 24th district)",
             "assigned":""
          },
          {
             "name":"Virginia Foxx (R-NR, 5th district)",
             "assigned":""
          },
          {
             "name":"Robert C. Bobby Scott (D-VA, 3rd district)",
             "assigned":""
          },
          {
             "name":"Jahana Hayes (D-CT, 5th district)",
             "assigned":""
          },
          {
             "name":"Mark DeSaulnier (D-CA, 11th district)",
             "assigned":""
          },
          {
             "name":"Donald Norcross (D-NJ, 1st district)",
             "assigned":""
          },
          {
             "name":"Dan Newhouse (R-WA, 4th district)",
             "assigned":""
          },
          {
             "name":"Susan Wild (D-PA, 7th district)",
             "assigned":""
          },
          {
             "name":"Scott Fitzgerald (R-WI, 5th district)",
             "assigned":""
          },
          {
             "name":"Julia Letlow (R-LA, 5th district)",
             "assigned":""
          },
          {
             "name":"Fred Keller (R-PA, 12th district)",
             "assigned":""
          },
          {
             "name":"Burgess Owens (R-UT, 4th district)",
             "assigned":""
          },
          {
             "name":"Tim Walberg (R-MI, 7th district)",
             "assigned":""
          },
          {
             "name":"Kweisi Mfume (D-MD, 7th district)",
             "assigned":""
          },
          {
             "name":"Jamaal Bowman (D-NY, 16th district)",
             "assigned":""
          },
          {
             "name":"Joaquin Castro (D-TX, 20th district)",
             "assigned":""
          },
          {
             "name":"Carolyn B. Maloney (D-NY, 12th district)",
             "assigned":""
          },
          {
             "name":"Gregory W. Meeks (D-NY, 5th district)",
             "assigned":""
          },
          {
             "name":"David Scott (D-GA, 13th district)",
             "assigned":""
          },
          {
             "name":"Patrick McHenry (R-NC, 10th district)",
             "assigned":""
          },
          {
             "name":"Trent Kelly (R-MS, 1st district)",
             "assigned":""
          },
          {
             "name":"Tom McClintock (R-CA, 4th district)",
             "assigned":""
          },
          {
             "name":"Glenn Grothman (R-WI, 6th district)",
             "assigned":""
          },
          {
             "name":"Lloyd Smucker (R-PA, 11th district)",
             "assigned":""
          },
          {
             "name":"Alma S. Adams (D-NC, 12th district)",
             "assigned":""
          },
          {
             "name":"Alexandria Ocasio-cCortez (D-NY, 14th district)",
             "assigned":""
          },
          {
             "name":"Donald Norcross (D-NJ, 1st district)",
             "assigned":""
          },
          {
             "name":"Eleanor Holmes Norton (D-DC, 1st district)",
             "assigned":""
          },
          {
             "name":"Eddie Bernice Johnson (D-TX, 30th district)",
             "assigned":""
          },
          {
             "name":"Rick Larsen (D-WA, 2nd district)",
             "assigned":""
          },
          {
             "name":"Thomas Massie (R-KY, 4th district)",
             "assigned":""
          },
          {
             "name":"Daniel Webster (R-FL, 11th district )",
             "assigned":""
          },
          {
             "name":"Scott Perry (R-PA, 10th district)",
             "assigned":""
          },
          {
             "name":"David Rouzer (R-NC, 7th district)",
             "assigned":""
          },
          {
             "name":"Doug LaMalfa (R-CA, 1st district)",
             "assigned":""
          },
          {
             "name":"Nydia Velázquez (D-NY, 7th district)",
             "assigned":""
          },
          {
             "name":"Alex Mooney (R-WV, 2nd district)",
             "assigned":""
          },
          {
             "name":"Blaine Luetkemeyer (R-MO, 3rd district)",
             "assigned":""
          },
          {
             "name":"Roger Williams (R-TX, 25th district)",
             "assigned":""
          },
          {
             "name":"Jim Hagedorn (R-MN, 1st district)",
             "assigned":""
          },
          {
             "name":"Sharice Davids (D-KS, 3rd district)",
             "assigned":""
          },
          {
             "name":"Morgan Griffith (R-VA, 9th district)",
             "assigned":""
          },
          {
             "name":"Claudia Tenney (R-NY, 22nd district)",
             "assigned":""
          },
          {
             "name":"Byron Donalds (R-FL,19th district)",
             "assigned":""
          },
          {
             "name":"Andrew Garbarino (R-NY, 2nd district)",
             "assigned":""
          }
       ]
    },
    {
       "committee":"WHO",
       "countries":[
          {
             "name":"Afghanistan",
             "assigned":""
          },
          {
             "name":"Algeria",
             "assigned":""
          },
          {
             "name":"Argentina",
             "assigned":""
          },
          {
             "name":"Austria",
             "assigned":""
          },
          {
             "name":"Bangladesh",
             "assigned":""
          },
          {
             "name":"Belarus",
             "assigned":""
          },
          {
             "name":"Belgium",
             "assigned":""
          },
          {
             "name":"Brazil",
             "assigned":""
          },
          {
             "name":"Brunei",
             "assigned":""
          },
          {
             "name":"Cambodia",
             "assigned":""
          },
          {
             "name":"Canada",
             "assigned":""
          },
          {
             "name":"Chad",
             "assigned":""
          },
          {
             "name":"Chile",
             "assigned":""
          },
          {
             "name":"China",
             "assigned":""
          },
          {
             "name":"Colombia",
             "assigned":""
          },
          {
             "name":"Congo",
             "assigned":""
          },
          {
             "name":"Costa Rica",
             "assigned":""
          },
          {
             "name":"Cote D Ivoire",
             "assigned":""
          },
          {
             "name":"Croatia",
             "assigned":""
          },
          {
             "name":"Cuba",
             "assigned":""
          },
          {
             "name":"Czech Republic",
             "assigned":""
          },
          {
             "name":"Denmark",
             "assigned":""
          },
          {
             "name":"Dominican Republic",
             "assigned":""
          },
          {
             "name":"DRC",
             "assigned":""
          },
          {
             "name":"Ecuador",
             "assigned":""
          },
          {
             "name":"Egypt",
             "assigned":""
          },
          {
             "name":"Ethiopia",
             "assigned":""
          },
          {
             "name":"Finland",
             "assigned":""
          },
          {
             "name":"France",
             "assigned":""
          },
          {
             "name":"Germany",
             "assigned":""
          },
          {
             "name":"Ghana",
             "assigned":""
          },
          {
             "name":"Greece",
             "assigned":""
          },
          {
             "name":"Haiti",
             "assigned":""
          },
          {
             "name":"Honduras",
             "assigned":""
          },
          {
             "name":"Hungary",
             "assigned":""
          },
          {
             "name":"India",
             "assigned":""
          },
          {
             "name":"Indonesia",
             "assigned":""
          },
          {
             "name":"Iraq",
             "assigned":""
          },
          {
             "name":"Ireland",
             "assigned":""
          },
          {
             "name":"Israel",
             "assigned":""
          },
          {
             "name":"Italy",
             "assigned":""
          },
          {
             "name":"Japan",
             "assigned":""
          },
          {
             "name":"Kazahstan",
             "assigned":""
          },
          {
             "name":"Kenya",
             "assigned":""
          },
          {
             "name":"Laos",
             "assigned":""
          },
          {
             "name":"Liberia",
             "assigned":""
          },
          {
             "name":"Libya",
             "assigned":""
          },
          {
             "name":"Madagascar",
             "assigned":""
          },
          {
             "name":"Malaysia",
             "assigned":""
          },
          {
             "name":"Maldives",
             "assigned":""
          },
          {
             "name":"Mali",
             "assigned":""
          },
          {
             "name":"Mexico",
             "assigned":""
          },
          {
             "name":"Mongolia",
             "assigned":""
          },
          {
             "name":"Morocco",
             "assigned":""
          },
          {
             "name":"Mozambique",
             "assigned":""
          },
          {
             "name":"Myanmmar",
             "assigned":""
          },
          {
             "name":"Nepal",
             "assigned":""
          },
          {
             "name":"Netherlands",
             "assigned":""
          },
          {
             "name":"New Zealand",
             "assigned":""
          },
          {
             "name":"Nigeria",
             "assigned":""
          },
          {
             "name":"North Korea",
             "assigned":""
          },
          {
             "name":"Norway",
             "assigned":""
          },
          {
             "name":"Pakistan",
             "assigned":""
          },
          {
             "name":"Peru",
             "assigned":""
          },
          {
             "name":"Phillipines",
             "assigned":""
          },
          {
             "name":"Poland",
             "assigned":""
          },
          {
             "name":"Portugal",
             "assigned":""
          },
          {
             "name":"Romania",
             "assigned":""
          },
          {
             "name":"Russia",
             "assigned":""
          },
          {
             "name":"Rwanda",
             "assigned":""
          },
          {
             "name":"Senegal",
             "assigned":""
          },
          {
             "name":"Serbia",
             "assigned":""
          },
          {
             "name":"Sierra Leone",
             "assigned":""
          },
          {
             "name":"Somalia",
             "assigned":""
          },
          {
             "name":"South Africa",
             "assigned":""
          },
          {
             "name":"South Korea",
             "assigned":""
          },
          {
             "name":"South Sudan",
             "assigned":""
          },
          {
             "name":"Spain",
             "assigned":""
          },
          {
             "name":"Sudan",
             "assigned":""
          },
          {
             "name":"Sweden",
             "assigned":""
          },
          {
             "name":"Switzerland",
             "assigned":""
          },
          {
             "name":"Syria",
             "assigned":""
          },
          {
             "name":"Tanzania",
             "assigned":""
          },
          {
             "name":"Thailand",
             "assigned":""
          },
          {
             "name":"Turkey",
             "assigned":""
          },
          {
             "name":"UAE",
             "assigned":""
          },
          {
             "name":"Uganda",
             "assigned":""
          },
          {
             "name":"Ukraine",
             "assigned":""
          },
          {
             "name":"United States",
             "assigned":""
          },
          {
             "name":"Uruguay",
             "assigned":""
          },
          {
             "name":"Venezuela",
             "assigned":""
          },
          {
             "name":"Viet Nam",
             "assigned":""
          },
          {
             "name":"Yemen",
             "assigned":""
          }
       ]
    }
 ]